FROM alpine:latest

ARG VERSION=latest
ARG TARGETARCH
ARG TARGETVARIANT

RUN apk add --no-cache tzdata tini bash ca-certificates gcompat libgcc libstdc++

COPY scripts/download.sh /download.sh
RUN apk add --no-cache --virtual .dl-deps curl unzip && \
    sed -i 's/\r$//' /download.sh && \
    chmod +x /download.sh && \
    /bin/bash /download.sh "$VERSION" "$TARGETARCH" "$TARGETVARIANT" && \
    rm -f /download.sh /usr/local/bin/easytier-core /usr/local/bin/easytier-cli && \
    apk del .dl-deps

COPY scripts/run_web.sh /run.sh
RUN sed -i 's/\r$//' /run.sh && chmod +x /run.sh

RUN mkdir -p /app/data/web
VOLUME /app/data
WORKDIR /app/data

ENTRYPOINT ["/sbin/tini", "--", "/run.sh"]
